#ifndef _GLFUNCRELOAD_
#define _GLFUNCRELOAD_

struct GLFunctionStruct;
typedef DWORD (CALLBACK * SetContextCallBack) (GLFunctionStruct *s);

typedef void (APIENTRY * PFNGLACCUMGLPROC)(GLenum op, GLfloat value);
typedef void (APIENTRY * PFNGLALPHAFUNCGLPROC)(GLenum func, GLclampf ref);
typedef GLboolean (APIENTRY * PFNGLARETEXTURESRESIDENTGLPROC)(GLsizei n, const GLuint *textures, GLboolean *residences);
typedef void (APIENTRY * PFNGLARRAYELEMENTGLPROC)(GLint i);
typedef void (APIENTRY * PFNGLBEGINGLPROC)(GLenum mode);
typedef void (APIENTRY * PFNGLBINDTEXTUREGLPROC)(GLenum target, GLuint texture);
typedef void (APIENTRY * PFNGLBITMAPGLPROC)(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
typedef void (APIENTRY * PFNGLBLENDFUNCGLPROC)(GLenum sfactor, GLenum dfactor);
typedef void (APIENTRY * PFNGLCALLLISTGLPROC)(GLuint list);
typedef void (APIENTRY * PFNGLCALLLISTSGLPROC)(GLsizei n, GLenum type, const GLvoid *lists);
typedef void (APIENTRY * PFNGLCLEARGLPROC)(GLbitfield mask);
typedef void (APIENTRY * PFNGLCLEARACCUMGLPROC)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
typedef void (APIENTRY * PFNGLCLEARCOLORGLPROC)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
typedef void (APIENTRY * PFNGLCLEARDEPTHGLPROC)(GLclampd depth);
typedef void (APIENTRY * PFNGLCLEARINDEXGLPROC)(GLfloat c);
typedef void (APIENTRY * PFNGLCLEARSTENCILGLPROC)(GLint s);
typedef void (APIENTRY * PFNGLCLIPPLANEGLPROC)(GLenum plane, const GLdouble *equation);
typedef void (APIENTRY * PFNGLCOLOR3BGLPROC)(GLbyte red, GLbyte green, GLbyte blue);
typedef void (APIENTRY * PFNGLCOLOR3BVGLPROC)(const GLbyte *v);
typedef void (APIENTRY * PFNGLCOLOR3DGLPROC)(GLdouble red, GLdouble green, GLdouble blue);
typedef void (APIENTRY * PFNGLCOLOR3DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLCOLOR3FGLPROC)(GLfloat red, GLfloat green, GLfloat blue);
typedef void (APIENTRY * PFNGLCOLOR3FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLCOLOR3IGLPROC)(GLint red, GLint green, GLint blue);
typedef void (APIENTRY * PFNGLCOLOR3IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLCOLOR3SGLPROC)(GLshort red, GLshort green, GLshort blue);
typedef void (APIENTRY * PFNGLCOLOR3SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLCOLOR3UBGLPROC)(GLubyte red, GLubyte green, GLubyte blue);
typedef void (APIENTRY * PFNGLCOLOR3UBVGLPROC)(const GLubyte *v);
typedef void (APIENTRY * PFNGLCOLOR3UIGLPROC)(GLuint red, GLuint green, GLuint blue);
typedef void (APIENTRY * PFNGLCOLOR3UIVGLPROC)(const GLuint *v);
typedef void (APIENTRY * PFNGLCOLOR3USGLPROC)(GLushort red, GLushort green, GLushort blue);
typedef void (APIENTRY * PFNGLCOLOR3USVGLPROC)(const GLushort *v);
typedef void (APIENTRY * PFNGLCOLOR4BGLPROC)(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
typedef void (APIENTRY * PFNGLCOLOR4BVGLPROC)(const GLbyte *v);
typedef void (APIENTRY * PFNGLCOLOR4DGLPROC)(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
typedef void (APIENTRY * PFNGLCOLOR4DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLCOLOR4FGLPROC)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
typedef void (APIENTRY * PFNGLCOLOR4FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLCOLOR4IGLPROC)(GLint red, GLint green, GLint blue, GLint alpha);
typedef void (APIENTRY * PFNGLCOLOR4IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLCOLOR4SGLPROC)(GLshort red, GLshort green, GLshort blue, GLshort alpha);
typedef void (APIENTRY * PFNGLCOLOR4SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLCOLOR4UBGLPROC)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
typedef void (APIENTRY * PFNGLCOLOR4UBVGLPROC)(const GLubyte *v);
typedef void (APIENTRY * PFNGLCOLOR4UIGLPROC)(GLuint red, GLuint green, GLuint blue, GLuint alpha);
typedef void (APIENTRY * PFNGLCOLOR4UIVGLPROC)(const GLuint *v);
typedef void (APIENTRY * PFNGLCOLOR4USGLPROC)(GLushort red, GLushort green, GLushort blue, GLushort alpha);
typedef void (APIENTRY * PFNGLCOLOR4USVGLPROC)(const GLushort *v);
typedef void (APIENTRY * PFNGLCOLORMASKGLPROC)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
typedef void (APIENTRY * PFNGLCOLORMATERIALGLPROC)(GLenum face, GLenum mode);
typedef void (APIENTRY * PFNGLCOLORPOINTERGLPROC)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * PFNGLCOPYPIXELSGLPROC)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
typedef void (APIENTRY * PFNGLCOPYTEXIMAGE1DGLPROC)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
typedef void (APIENTRY * PFNGLCOPYTEXIMAGE2DGLPROC)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
typedef void (APIENTRY * PFNGLCOPYTEXSUBIMAGE1DGLPROC)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
typedef void (APIENTRY * PFNGLCOPYTEXSUBIMAGE2DGLPROC)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
typedef void (APIENTRY * PFNGLCULLFACEGLPROC)(GLenum mode);
typedef void (APIENTRY * PFNGLDELETELISTSGLPROC)(GLuint list, GLsizei range);
typedef void (APIENTRY * PFNGLDELETETEXTURESGLPROC)(GLsizei n, const GLuint *textures);
typedef void (APIENTRY * PFNGLDEPTHFUNCGLPROC)(GLenum func);
typedef void (APIENTRY * PFNGLDEPTHMASKGLPROC)(GLboolean flag);
typedef void (APIENTRY * PFNGLDEPTHRANGEGLPROC)(GLclampd zNear, GLclampd zFar);
typedef void (APIENTRY * PFNGLDISABLEGLPROC)(GLenum cap);
typedef void (APIENTRY * PFNGLDISABLECLIENTSTATEGLPROC)(GLenum array);
typedef void (APIENTRY * PFNGLDRAWARRAYSGLPROC)(GLenum mode, GLint first, GLsizei count);
typedef void (APIENTRY * PFNGLDRAWBUFFERGLPROC)(GLenum mode);
typedef void (APIENTRY * PFNGLDRAWELEMENTSGLPROC)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
typedef void (APIENTRY * PFNGLDRAWPIXELSGLPROC)(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * PFNGLEDGEFLAGGLPROC)(GLboolean flag);
typedef void (APIENTRY * PFNGLEDGEFLAGPOINTERGLPROC)(GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * PFNGLEDGEFLAGVGLPROC)(const GLboolean *flag);
typedef void (APIENTRY * PFNGLENABLEGLPROC)(GLenum cap);
typedef void (APIENTRY * PFNGLENABLECLIENTSTATEGLPROC)(GLenum array);
typedef void (APIENTRY * PFNGLENDGLPROC)(void);
typedef void (APIENTRY * PFNGLENDLISTGLPROC)(void);
typedef void (APIENTRY * PFNGLEVALCOORD1DGLPROC)(GLdouble u);
typedef void (APIENTRY * PFNGLEVALCOORD1DVGLPROC)(const GLdouble *u);
typedef void (APIENTRY * PFNGLEVALCOORD1FGLPROC)(GLfloat u);
typedef void (APIENTRY * PFNGLEVALCOORD1FVGLPROC)(const GLfloat *u);
typedef void (APIENTRY * PFNGLEVALCOORD2DGLPROC)(GLdouble u, GLdouble v);
typedef void (APIENTRY * PFNGLEVALCOORD2DVGLPROC)(const GLdouble *u);
typedef void (APIENTRY * PFNGLEVALCOORD2FGLPROC)(GLfloat u, GLfloat v);
typedef void (APIENTRY * PFNGLEVALCOORD2FVGLPROC)(const GLfloat *u);
typedef void (APIENTRY * PFNGLEVALMESH1GLPROC)(GLenum mode, GLint i1, GLint i2);
typedef void (APIENTRY * PFNGLEVALMESH2GLPROC)(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
typedef void (APIENTRY * PFNGLEVALPOINT1GLPROC)(GLint i);
typedef void (APIENTRY * PFNGLEVALPOINT2GLPROC)(GLint i, GLint j);
typedef void (APIENTRY * PFNGLFEEDBACKBUFFERGLPROC)(GLsizei size, GLenum type, GLfloat *buffer);
typedef void (APIENTRY * PFNGLFINISHGLPROC)(void);
typedef void (APIENTRY * PFNGLFLUSHGLPROC)(void);
typedef void (APIENTRY * PFNGLFOGFGLPROC)(GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLFOGFVGLPROC)(GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLFOGIGLPROC)(GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLFOGIVGLPROC)(GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLFRONTFACEGLPROC)(GLenum mode);
typedef void (APIENTRY * PFNGLFRUSTUMGLPROC)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
typedef GLuint (APIENTRY * PFNGLGENLISTSGLPROC)(GLsizei range);
typedef void (APIENTRY * PFNGLGENTEXTURESGLPROC)(GLsizei n, GLuint *textures);
typedef void (APIENTRY * PFNGLGETBOOLEANVGLPROC)(GLenum pname, GLboolean *params);
typedef void (APIENTRY * PFNGLGETCLIPPLANEGLPROC)(GLenum plane, GLdouble *equation);
typedef void (APIENTRY * PFNGLGETDOUBLEVGLPROC)(GLenum pname, GLdouble *params);
typedef GLenum (APIENTRY * PFNGLGETERRORGLPROC)(void);
typedef void (APIENTRY * PFNGLGETFLOATVGLPROC)(GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETINTEGERVGLPROC)(GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETLIGHTFVGLPROC)(GLenum light, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETLIGHTIVGLPROC)(GLenum light, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETMAPDVGLPROC)(GLenum target, GLenum query, GLdouble *v);
typedef void (APIENTRY * PFNGLGETMAPFVGLPROC)(GLenum target, GLenum query, GLfloat *v);
typedef void (APIENTRY * PFNGLGETMAPIVGLPROC)(GLenum target, GLenum query, GLint *v);
typedef void (APIENTRY * PFNGLGETMATERIALFVGLPROC)(GLenum face, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETMATERIALIVGLPROC)(GLenum face, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETPIXELMAPFVGLPROC)(GLenum map, GLfloat *values);
typedef void (APIENTRY * PFNGLGETPIXELMAPUIVGLPROC)(GLenum map, GLuint *values);
typedef void (APIENTRY * PFNGLGETPIXELMAPUSVGLPROC)(GLenum map, GLushort *values);
typedef void (APIENTRY * PFNGLGETPOINTERVGLPROC)(GLenum pname, GLvoid* *params);
typedef void (APIENTRY * PFNGLGETPOLYGONSTIPPLEGLPROC)(GLubyte *mask);
typedef const GLubyte * (APIENTRY * PFNGLGETSTRINGGLPROC)(GLenum name);
typedef void (APIENTRY * PFNGLGETTEXENVFVGLPROC)(GLenum target, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETTEXENVIVGLPROC)(GLenum target, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETTEXGENDVGLPROC)(GLenum coord, GLenum pname, GLdouble *params);
typedef void (APIENTRY * PFNGLGETTEXGENFVGLPROC)(GLenum coord, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETTEXGENIVGLPROC)(GLenum coord, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETTEXIMAGEGLPROC)(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
typedef void (APIENTRY * PFNGLGETTEXLEVELPARAMETERFVGLPROC)(GLenum target, GLint level, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETTEXLEVELPARAMETERIVGLPROC)(GLenum target, GLint level, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETTEXPARAMETERFVGLPROC)(GLenum target, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETTEXPARAMETERIVGLPROC)(GLenum target, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLHINTGLPROC)(GLenum target, GLenum mode);
typedef void (APIENTRY * PFNGLINDEXMASKGLPROC)(GLuint mask);
typedef void (APIENTRY * PFNGLINDEXPOINTERGLPROC)(GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * PFNGLINDEXDGLPROC)(GLdouble c);
typedef void (APIENTRY * PFNGLINDEXDVGLPROC)(const GLdouble *c);
typedef void (APIENTRY * PFNGLINDEXFGLPROC)(GLfloat c);
typedef void (APIENTRY * PFNGLINDEXFVGLPROC)(const GLfloat *c);
typedef void (APIENTRY * PFNGLINDEXIGLPROC)(GLint c);
typedef void (APIENTRY * PFNGLINDEXIVGLPROC)(const GLint *c);
typedef void (APIENTRY * PFNGLINDEXSGLPROC)(GLshort c);
typedef void (APIENTRY * PFNGLINDEXSVGLPROC)(const GLshort *c);
typedef void (APIENTRY * PFNGLINDEXUBGLPROC)(GLubyte c);
typedef void (APIENTRY * PFNGLINDEXUBVGLPROC)(const GLubyte *c);
typedef void (APIENTRY * PFNGLINITNAMESGLPROC)(void);
typedef void (APIENTRY * PFNGLINTERLEAVEDARRAYSGLPROC)(GLenum format, GLsizei stride, const GLvoid *pointer);
typedef GLboolean (APIENTRY * PFNGLISENABLEDGLPROC)(GLenum cap);
typedef GLboolean (APIENTRY * PFNGLISLISTGLPROC)(GLuint list);
typedef GLboolean (APIENTRY * PFNGLISTEXTUREGLPROC)(GLuint texture);
typedef void (APIENTRY * PFNGLLIGHTMODELFGLPROC)(GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLLIGHTMODELFVGLPROC)(GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLLIGHTMODELIGLPROC)(GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLLIGHTMODELIVGLPROC)(GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLLIGHTFGLPROC)(GLenum light, GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLLIGHTFVGLPROC)(GLenum light, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLLIGHTIGLPROC)(GLenum light, GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLLIGHTIVGLPROC)(GLenum light, GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLLINESTIPPLEGLPROC)(GLint factor, GLushort pattern);
typedef void (APIENTRY * PFNGLLINEWIDTHGLPROC)(GLfloat width);
typedef void (APIENTRY * PFNGLLISTBASEGLPROC)(GLuint base);
typedef void (APIENTRY * PFNGLLOADIDENTITYGLPROC)(void);
typedef void (APIENTRY * PFNGLLOADMATRIXDGLPROC)(const GLdouble *m);
typedef void (APIENTRY * PFNGLLOADMATRIXFGLPROC)(const GLfloat *m);
typedef void (APIENTRY * PFNGLLOADNAMEGLPROC)(GLuint name);
typedef void (APIENTRY * PFNGLLOGICOPGLPROC)(GLenum opcode);
typedef void (APIENTRY * PFNGLMAP1DGLPROC)(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
typedef void (APIENTRY * PFNGLMAP1FGLPROC)(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
typedef void (APIENTRY * PFNGLMAP2DGLPROC)(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
typedef void (APIENTRY * PFNGLMAP2FGLPROC)(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
typedef void (APIENTRY * PFNGLMAPGRID1DGLPROC)(GLint un, GLdouble u1, GLdouble u2);
typedef void (APIENTRY * PFNGLMAPGRID1FGLPROC)(GLint un, GLfloat u1, GLfloat u2);
typedef void (APIENTRY * PFNGLMAPGRID2DGLPROC)(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
typedef void (APIENTRY * PFNGLMAPGRID2FGLPROC)(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
typedef void (APIENTRY * PFNGLMATERIALFGLPROC)(GLenum face, GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLMATERIALFVGLPROC)(GLenum face, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLMATERIALIGLPROC)(GLenum face, GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLMATERIALIVGLPROC)(GLenum face, GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLMATRIXMODEGLPROC)(GLenum mode);
typedef void (APIENTRY * PFNGLMULTMATRIXDGLPROC)(const GLdouble *m);
typedef void (APIENTRY * PFNGLMULTMATRIXFGLPROC)(const GLfloat *m);
typedef void (APIENTRY * PFNGLNEWLISTGLPROC)(GLuint list, GLenum mode);
typedef void (APIENTRY * PFNGLNORMAL3BGLPROC)(GLbyte nx, GLbyte ny, GLbyte nz);
typedef void (APIENTRY * PFNGLNORMAL3BVGLPROC)(const GLbyte *v);
typedef void (APIENTRY * PFNGLNORMAL3DGLPROC)(GLdouble nx, GLdouble ny, GLdouble nz);
typedef void (APIENTRY * PFNGLNORMAL3DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLNORMAL3FGLPROC)(GLfloat nx, GLfloat ny, GLfloat nz);
typedef void (APIENTRY * PFNGLNORMAL3FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLNORMAL3IGLPROC)(GLint nx, GLint ny, GLint nz);
typedef void (APIENTRY * PFNGLNORMAL3IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLNORMAL3SGLPROC)(GLshort nx, GLshort ny, GLshort nz);
typedef void (APIENTRY * PFNGLNORMAL3SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLNORMALPOINTERGLPROC)(GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * PFNGLORTHOGLPROC)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
typedef void (APIENTRY * PFNGLPASSTHROUGHGLPROC)(GLfloat token);
typedef void (APIENTRY * PFNGLPIXELMAPFVGLPROC)(GLenum map, GLsizei mapsize, const GLfloat *values);
typedef void (APIENTRY * PFNGLPIXELMAPUIVGLPROC)(GLenum map, GLsizei mapsize, const GLuint *values);
typedef void (APIENTRY * PFNGLPIXELMAPUSVGLPROC)(GLenum map, GLsizei mapsize, const GLushort *values);
typedef void (APIENTRY * PFNGLPIXELSTOREFGLPROC)(GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLPIXELSTOREIGLPROC)(GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLPIXELTRANSFERFGLPROC)(GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLPIXELTRANSFERIGLPROC)(GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLPIXELZOOMGLPROC)(GLfloat xfactor, GLfloat yfactor);
typedef void (APIENTRY * PFNGLPOINTSIZEGLPROC)(GLfloat size);
typedef void (APIENTRY * PFNGLPOLYGONMODEGLPROC)(GLenum face, GLenum mode);
typedef void (APIENTRY * PFNGLPOLYGONOFFSETGLPROC)(GLfloat factor, GLfloat units);
typedef void (APIENTRY * PFNGLPOLYGONSTIPPLEGLPROC)(const GLubyte *mask);
typedef void (APIENTRY * PFNGLPOPATTRIBGLPROC)(void);
typedef void (APIENTRY * PFNGLPOPCLIENTATTRIBGLPROC)(void);
typedef void (APIENTRY * PFNGLPOPMATRIXGLPROC)(void);
typedef void (APIENTRY * PFNGLPOPNAMEGLPROC)(void);
typedef void (APIENTRY * PFNGLPRIORITIZETEXTURESGLPROC)(GLsizei n, const GLuint *textures, const GLclampf *priorities);
typedef void (APIENTRY * PFNGLPUSHATTRIBGLPROC)(GLbitfield mask);
typedef void (APIENTRY * PFNGLPUSHCLIENTATTRIBGLPROC)(GLbitfield mask);
typedef void (APIENTRY * PFNGLPUSHMATRIXGLPROC)(void);
typedef void (APIENTRY * PFNGLPUSHNAMEGLPROC)(GLuint name);
typedef void (APIENTRY * PFNGLRASTERPOS2DGLPROC)(GLdouble x, GLdouble y);
typedef void (APIENTRY * PFNGLRASTERPOS2DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLRASTERPOS2FGLPROC)(GLfloat x, GLfloat y);
typedef void (APIENTRY * PFNGLRASTERPOS2FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLRASTERPOS2IGLPROC)(GLint x, GLint y);
typedef void (APIENTRY * PFNGLRASTERPOS2IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLRASTERPOS2SGLPROC)(GLshort x, GLshort y);
typedef void (APIENTRY * PFNGLRASTERPOS2SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLRASTERPOS3DGLPROC)(GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * PFNGLRASTERPOS3DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLRASTERPOS3FGLPROC)(GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * PFNGLRASTERPOS3FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLRASTERPOS3IGLPROC)(GLint x, GLint y, GLint z);
typedef void (APIENTRY * PFNGLRASTERPOS3IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLRASTERPOS3SGLPROC)(GLshort x, GLshort y, GLshort z);
typedef void (APIENTRY * PFNGLRASTERPOS3SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLRASTERPOS4DGLPROC)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
typedef void (APIENTRY * PFNGLRASTERPOS4DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLRASTERPOS4FGLPROC)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
typedef void (APIENTRY * PFNGLRASTERPOS4FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLRASTERPOS4IGLPROC)(GLint x, GLint y, GLint z, GLint w);
typedef void (APIENTRY * PFNGLRASTERPOS4IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLRASTERPOS4SGLPROC)(GLshort x, GLshort y, GLshort z, GLshort w);
typedef void (APIENTRY * PFNGLRASTERPOS4SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLREADBUFFERGLPROC)(GLenum mode);
typedef void (APIENTRY * PFNGLREADPIXELSGLPROC)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
typedef void (APIENTRY * PFNGLRECTDGLPROC)(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
typedef void (APIENTRY * PFNGLRECTDVGLPROC)(const GLdouble *v1, const GLdouble *v2);
typedef void (APIENTRY * PFNGLRECTFGLPROC)(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
typedef void (APIENTRY * PFNGLRECTFVGLPROC)(const GLfloat *v1, const GLfloat *v2);
typedef void (APIENTRY * PFNGLRECTIGLPROC)(GLint x1, GLint y1, GLint x2, GLint y2);
typedef void (APIENTRY * PFNGLRECTIVGLPROC)(const GLint *v1, const GLint *v2);
typedef void (APIENTRY * PFNGLRECTSGLPROC)(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
typedef void (APIENTRY * PFNGLRECTSVGLPROC)(const GLshort *v1, const GLshort *v2);
typedef GLint (APIENTRY * PFNGLRENDERMODEGLPROC)(GLenum mode);
typedef void (APIENTRY * PFNGLROTATEDGLPROC)(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * PFNGLROTATEFGLPROC)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * PFNGLSCALEDGLPROC)(GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * PFNGLSCALEFGLPROC)(GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * PFNGLSCISSORGLPROC)(GLint x, GLint y, GLsizei width, GLsizei height);
typedef void (APIENTRY * PFNGLSELECTBUFFERGLPROC)(GLsizei size, GLuint *buffer);
typedef void (APIENTRY * PFNGLSHADEMODELGLPROC)(GLenum mode);
typedef void (APIENTRY * PFNGLSTENCILFUNCGLPROC)(GLenum func, GLint ref, GLuint mask);
typedef void (APIENTRY * PFNGLSTENCILMASKGLPROC)(GLuint mask);
typedef void (APIENTRY * PFNGLSTENCILOPGLPROC)(GLenum fail, GLenum zfail, GLenum zpass);
typedef void (APIENTRY * PFNGLTEXCOORD1DGLPROC)(GLdouble s);
typedef void (APIENTRY * PFNGLTEXCOORD1DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLTEXCOORD1FGLPROC)(GLfloat s);
typedef void (APIENTRY * PFNGLTEXCOORD1FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLTEXCOORD1IGLPROC)(GLint s);
typedef void (APIENTRY * PFNGLTEXCOORD1IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLTEXCOORD1SGLPROC)(GLshort s);
typedef void (APIENTRY * PFNGLTEXCOORD1SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLTEXCOORD2DGLPROC)(GLdouble s, GLdouble t);
typedef void (APIENTRY * PFNGLTEXCOORD2DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLTEXCOORD2FGLPROC)(GLfloat s, GLfloat t);
typedef void (APIENTRY * PFNGLTEXCOORD2FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLTEXCOORD2IGLPROC)(GLint s, GLint t);
typedef void (APIENTRY * PFNGLTEXCOORD2IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLTEXCOORD2SGLPROC)(GLshort s, GLshort t);
typedef void (APIENTRY * PFNGLTEXCOORD2SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLTEXCOORD3DGLPROC)(GLdouble s, GLdouble t, GLdouble r);
typedef void (APIENTRY * PFNGLTEXCOORD3DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLTEXCOORD3FGLPROC)(GLfloat s, GLfloat t, GLfloat r);
typedef void (APIENTRY * PFNGLTEXCOORD3FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLTEXCOORD3IGLPROC)(GLint s, GLint t, GLint r);
typedef void (APIENTRY * PFNGLTEXCOORD3IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLTEXCOORD3SGLPROC)(GLshort s, GLshort t, GLshort r);
typedef void (APIENTRY * PFNGLTEXCOORD3SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLTEXCOORD4DGLPROC)(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
typedef void (APIENTRY * PFNGLTEXCOORD4DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLTEXCOORD4FGLPROC)(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
typedef void (APIENTRY * PFNGLTEXCOORD4FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLTEXCOORD4IGLPROC)(GLint s, GLint t, GLint r, GLint q);
typedef void (APIENTRY * PFNGLTEXCOORD4IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLTEXCOORD4SGLPROC)(GLshort s, GLshort t, GLshort r, GLshort q);
typedef void (APIENTRY * PFNGLTEXCOORD4SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLTEXCOORDPOINTERGLPROC)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * PFNGLTEXENVFGLPROC)(GLenum target, GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLTEXENVFVGLPROC)(GLenum target, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLTEXENVIGLPROC)(GLenum target, GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLTEXENVIVGLPROC)(GLenum target, GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLTEXGENDGLPROC)(GLenum coord, GLenum pname, GLdouble param);
typedef void (APIENTRY * PFNGLTEXGENDVGLPROC)(GLenum coord, GLenum pname, const GLdouble *params);
typedef void (APIENTRY * PFNGLTEXGENFGLPROC)(GLenum coord, GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLTEXGENFVGLPROC)(GLenum coord, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLTEXGENIGLPROC)(GLenum coord, GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLTEXGENIVGLPROC)(GLenum coord, GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLTEXIMAGE1DGLPROC)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * PFNGLTEXIMAGE2DGLPROC)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * PFNGLTEXPARAMETERFGLPROC)(GLenum target, GLenum pname, GLfloat param);
typedef void (APIENTRY * PFNGLTEXPARAMETERFVGLPROC)(GLenum target, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLTEXPARAMETERIGLPROC)(GLenum target, GLenum pname, GLint param);
typedef void (APIENTRY * PFNGLTEXPARAMETERIVGLPROC)(GLenum target, GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLTEXSUBIMAGE1DGLPROC)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * PFNGLTEXSUBIMAGE2DGLPROC)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
typedef void (APIENTRY * PFNGLTRANSLATEDGLPROC)(GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * PFNGLTRANSLATEFGLPROC)(GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * PFNGLVERTEX2DGLPROC)(GLdouble x, GLdouble y);
typedef void (APIENTRY * PFNGLVERTEX2DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLVERTEX2FGLPROC)(GLfloat x, GLfloat y);
typedef void (APIENTRY * PFNGLVERTEX2FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLVERTEX2IGLPROC)(GLint x, GLint y);
typedef void (APIENTRY * PFNGLVERTEX2IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLVERTEX2SGLPROC)(GLshort x, GLshort y);
typedef void (APIENTRY * PFNGLVERTEX2SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLVERTEX3DGLPROC)(GLdouble x, GLdouble y, GLdouble z);
typedef void (APIENTRY * PFNGLVERTEX3DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLVERTEX3FGLPROC)(GLfloat x, GLfloat y, GLfloat z);
typedef void (APIENTRY * PFNGLVERTEX3FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLVERTEX3IGLPROC)(GLint x, GLint y, GLint z);
typedef void (APIENTRY * PFNGLVERTEX3IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLVERTEX3SGLPROC)(GLshort x, GLshort y, GLshort z);
typedef void (APIENTRY * PFNGLVERTEX3SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLVERTEX4DGLPROC)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
typedef void (APIENTRY * PFNGLVERTEX4DVGLPROC)(const GLdouble *v);
typedef void (APIENTRY * PFNGLVERTEX4FGLPROC)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
typedef void (APIENTRY * PFNGLVERTEX4FVGLPROC)(const GLfloat *v);
typedef void (APIENTRY * PFNGLVERTEX4IGLPROC)(GLint x, GLint y, GLint z, GLint w);
typedef void (APIENTRY * PFNGLVERTEX4IVGLPROC)(const GLint *v);
typedef void (APIENTRY * PFNGLVERTEX4SGLPROC)(GLshort x, GLshort y, GLshort z, GLshort w);
typedef void (APIENTRY * PFNGLVERTEX4SVGLPROC)(const GLshort *v);
typedef void (APIENTRY * PFNGLVERTEXPOINTERGLPROC)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void (APIENTRY * PFNGLVIEWPORTGLPROC)(GLint x, GLint y, GLsizei width, GLsizei height);
typedef BOOL (WINAPI * PFNWGLUSEFONTOUTLINESAGLPROC)(HDC hdc, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf );
typedef BOOL (WINAPI * PFNWGLUSEFONTOUTLINESWGLPROC)(HDC hdc, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf );
typedef BOOL (WINAPI * PFNWGLUSEFONTBITMAPSAGLPROC)(HDC hdc, DWORD first, DWORD count, DWORD listBase);
typedef BOOL (WINAPI * PFNWGLUSEFONTBITMAPSWGLPROC)(HDC hdc, DWORD first, DWORD count, DWORD listBase);
typedef BOOL (WINAPI * PFNWGLCOPYCONTEXTGLPROC)(HGLRC hglrcSrc, HGLRC hglrcDst, UINT mask);
typedef HGLRC (WINAPI * PFNWGLCREATECONTEXTGLPROC)(HDC hdc);
typedef HGLRC (WINAPI * PFNWGLCREATELAYERCONTEXTGLPROC)(HDC hdc, int iLayerPlane);
typedef BOOL (WINAPI * PFNWGLDELETECONTEXTGLPROC)(HGLRC hglrc);
typedef HGLRC (WINAPI * PFNWGLGETCURRENTCONTEXTGLPROC)(VOID);
typedef HDC (WINAPI * PFNWGLGETCURRENTDCGLPROC)(VOID);
typedef PROC (WINAPI * PFNWGLGETPROCADDRESSGLPROC)(LPCSTR lpszProc);
typedef BOOL (WINAPI * PFNWGLMAKECURRENTGLPROC)(HDC hdc, HGLRC hglrc);
typedef BOOL (WINAPI * PFNWGLSHARELISTSGLPROC)(HGLRC hglrc1, HGLRC hglrc2);
typedef BOOL (WINAPI * PFNWGLDESCRIBELAYERPLANEGLPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nBytes, LPLAYERPLANEDESCRIPTOR plpd);
typedef int (WINAPI * PFNWGLSETLAYERPALETTEENTRIESGLPROC)(HDC hdc, int iLayerPlane, int iStart, int cEntries, CONST COLORREF *pcr);
typedef int (WINAPI * PFNWGLGETLAYERPALETTEENTRIESGLPROC)(HDC hdc, int iLayerPlane, int iStart, int cEntries, COLORREF *pcr);
typedef BOOL (WINAPI * PFNWGLREALIZELAYERPALETTEGLPROC)(HDC hdc, int iLayerPlane, BOOL bRealize);
typedef BOOL (WINAPI * PFNWGLSWAPLAYERBUFFERSGLPROC)(HDC hdc, UINT fuPlanes);
typedef int (WINAPI * PFNWGLCHOOSEPIXELFORMATGLPROC)(HDC hdc, CONST PIXELFORMATDESCRIPTOR * ppfd);
typedef int (WINAPI * PFNWGLDESCRIBEPIXELFORMATGLPROC)(HDC hdc, int iPixelFormat, UINT nBytes, LPPIXELFORMATDESCRIPTOR ppfd);
typedef int (WINAPI * PFNWGLGETPIXELFORMATGLPROC)(HDC hdc);
typedef BOOL (WINAPI * PFNWGLSETPIXELFORMATGLPROC)(HDC hdc, int iPixelFormat, CONST PIXELFORMATDESCRIPTOR * ppfd);
typedef BOOL (WINAPI * PFNWGLSWAPBUFFERSGLPROC)(HDC hdc);
typedef DWORD (WINAPI * PFNWGLGETDEFAULTPROCADDRESSGLPROC)(void);
typedef BOOL (WINAPI * PFNDRVCOPYCONTEXTGLPROC)(HGLRC hglrcSrc, HGLRC hglrcDst, UINT mask);
typedef HGLRC (WINAPI * PFNDRVCREATECONTEXTGLPROC)(HDC hdc);
typedef HGLRC (WINAPI * PFNDRVCREATELAYERCONTEXTGLPROC)(HDC hdc, int iLayerPlane);
typedef BOOL (WINAPI * PFNDRVDELETECONTEXTGLPROC)(HGLRC hglrc);
typedef BOOL (WINAPI * PFNDRVDESCRIBELAYERPLANEGLPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nBytes, LPLAYERPLANEDESCRIPTOR plpd);
typedef int (WINAPI * PFNDRVDESCRIBEPIXELFORMATGLPROC)(HDC hdc, int iPixelFormat, UINT nBytes, LPPIXELFORMATDESCRIPTOR ppfd);
typedef int (WINAPI * PFNDRVSETLAYERPALETTEENTRIESGLPROC)(HDC hdc, int iLayerPlane, int iStart, int cEntries, CONST COLORREF *pcr);
typedef int (WINAPI * PFNDRVGETLAYERPALETTEENTRIESGLPROC)(HDC hdc, int iLayerPlane, int iStart, int cEntries, COLORREF *pcr);
typedef BOOL (WINAPI * PFNDRVREALIZELAYERPALETTEGLPROC)(HDC hdc, int iLayerPlane, BOOL bRealize);
typedef BOOL (WINAPI * PFNDRVSWAPLAYERBUFFERSGLPROC)(HDC hdc, UINT fuPlanes);
typedef BOOL (WINAPI * PFNDRVSHARELISTSGLPROC)(HGLRC hglrc1, HGLRC hglrc2);
typedef BOOL (WINAPI * PFNDRVSETPIXELFORMATGLPROC)(HDC hdc, int iPixelFormat, CONST PIXELFORMATDESCRIPTOR * ppfd);
typedef BOOL (WINAPI * PFNDRVSWAPBUFFERSGLPROC)(HDC hdc);
typedef PROC (WINAPI * PFNDRVGETPROCADDRESSGLPROC)(LPCSTR lpszProc);
typedef int (WINAPI * PFNDRVSETCONTEXTGLPROC)(HDC hdc, HGLRC hglrc, SetContextCallBack callback);
typedef DWORD (WINAPI * PFNDRVRELEASECONTEXTGLPROC)(VOID);
typedef DWORD (WINAPI * PFNDRVVALIDATEVERSIONGLPROC)(VOID);

extern PFNGLACCUMGLPROC _glAccum;
extern PFNGLALPHAFUNCGLPROC _glAlphaFunc;
extern PFNGLARETEXTURESRESIDENTGLPROC _glAreTexturesResident;
extern PFNGLARRAYELEMENTGLPROC _glArrayElement;
extern PFNGLBEGINGLPROC _glBegin;
extern PFNGLBINDTEXTUREGLPROC _glBindTexture;
extern PFNGLBITMAPGLPROC _glBitmap;
extern PFNGLBLENDFUNCGLPROC _glBlendFunc;
extern PFNGLCALLLISTGLPROC _glCallList;
extern PFNGLCALLLISTSGLPROC _glCallLists;
extern PFNGLCLEARGLPROC _glClear;
extern PFNGLCLEARACCUMGLPROC _glClearAccum;
extern PFNGLCLEARCOLORGLPROC _glClearColor;
extern PFNGLCLEARDEPTHGLPROC _glClearDepth;
extern PFNGLCLEARINDEXGLPROC _glClearIndex;
extern PFNGLCLEARSTENCILGLPROC _glClearStencil;
extern PFNGLCLIPPLANEGLPROC _glClipPlane;
extern PFNGLCOLOR3BGLPROC _glColor3b;
extern PFNGLCOLOR3BVGLPROC _glColor3bv;
extern PFNGLCOLOR3DGLPROC _glColor3d;
extern PFNGLCOLOR3DVGLPROC _glColor3dv;
extern PFNGLCOLOR3FGLPROC _glColor3f;
extern PFNGLCOLOR3FVGLPROC _glColor3fv;
extern PFNGLCOLOR3IGLPROC _glColor3i;
extern PFNGLCOLOR3IVGLPROC _glColor3iv;
extern PFNGLCOLOR3SGLPROC _glColor3s;
extern PFNGLCOLOR3SVGLPROC _glColor3sv;
extern PFNGLCOLOR3UBGLPROC _glColor3ub;
extern PFNGLCOLOR3UBVGLPROC _glColor3ubv;
extern PFNGLCOLOR3UIGLPROC _glColor3ui;
extern PFNGLCOLOR3UIVGLPROC _glColor3uiv;
extern PFNGLCOLOR3USGLPROC _glColor3us;
extern PFNGLCOLOR3USVGLPROC _glColor3usv;
extern PFNGLCOLOR4BGLPROC _glColor4b;
extern PFNGLCOLOR4BVGLPROC _glColor4bv;
extern PFNGLCOLOR4DGLPROC _glColor4d;
extern PFNGLCOLOR4DVGLPROC _glColor4dv;
extern PFNGLCOLOR4FGLPROC _glColor4f;
extern PFNGLCOLOR4FVGLPROC _glColor4fv;
extern PFNGLCOLOR4IGLPROC _glColor4i;
extern PFNGLCOLOR4IVGLPROC _glColor4iv;
extern PFNGLCOLOR4SGLPROC _glColor4s;
extern PFNGLCOLOR4SVGLPROC _glColor4sv;
extern PFNGLCOLOR4UBGLPROC _glColor4ub;
extern PFNGLCOLOR4UBVGLPROC _glColor4ubv;
extern PFNGLCOLOR4UIGLPROC _glColor4ui;
extern PFNGLCOLOR4UIVGLPROC _glColor4uiv;
extern PFNGLCOLOR4USGLPROC _glColor4us;
extern PFNGLCOLOR4USVGLPROC _glColor4usv;
extern PFNGLCOLORMASKGLPROC _glColorMask;
extern PFNGLCOLORMATERIALGLPROC _glColorMaterial;
extern PFNGLCOLORPOINTERGLPROC _glColorPointer;
extern PFNGLCOPYPIXELSGLPROC _glCopyPixels;
extern PFNGLCOPYTEXIMAGE1DGLPROC _glCopyTexImage1D;
extern PFNGLCOPYTEXIMAGE2DGLPROC _glCopyTexImage2D;
extern PFNGLCOPYTEXSUBIMAGE1DGLPROC _glCopyTexSubImage1D;
extern PFNGLCOPYTEXSUBIMAGE2DGLPROC _glCopyTexSubImage2D;
extern PFNGLCULLFACEGLPROC _glCullFace;
extern PFNGLDELETELISTSGLPROC _glDeleteLists;
extern PFNGLDELETETEXTURESGLPROC _glDeleteTextures;
extern PFNGLDEPTHFUNCGLPROC _glDepthFunc;
extern PFNGLDEPTHMASKGLPROC _glDepthMask;
extern PFNGLDEPTHRANGEGLPROC _glDepthRange;
extern PFNGLDISABLEGLPROC _glDisable;
extern PFNGLDISABLECLIENTSTATEGLPROC _glDisableClientState;
extern PFNGLDRAWARRAYSGLPROC _glDrawArrays;
extern PFNGLDRAWBUFFERGLPROC _glDrawBuffer;
extern PFNGLDRAWELEMENTSGLPROC _glDrawElements;
extern PFNGLDRAWPIXELSGLPROC _glDrawPixels;
extern PFNGLEDGEFLAGGLPROC _glEdgeFlag;
extern PFNGLEDGEFLAGPOINTERGLPROC _glEdgeFlagPointer;
extern PFNGLEDGEFLAGVGLPROC _glEdgeFlagv;
extern PFNGLENABLEGLPROC _glEnable;
extern PFNGLENABLECLIENTSTATEGLPROC _glEnableClientState;
extern PFNGLENDGLPROC _glEnd;
extern PFNGLENDLISTGLPROC _glEndList;
extern PFNGLEVALCOORD1DGLPROC _glEvalCoord1d;
extern PFNGLEVALCOORD1DVGLPROC _glEvalCoord1dv;
extern PFNGLEVALCOORD1FGLPROC _glEvalCoord1f;
extern PFNGLEVALCOORD1FVGLPROC _glEvalCoord1fv;
extern PFNGLEVALCOORD2DGLPROC _glEvalCoord2d;
extern PFNGLEVALCOORD2DVGLPROC _glEvalCoord2dv;
extern PFNGLEVALCOORD2FGLPROC _glEvalCoord2f;
extern PFNGLEVALCOORD2FVGLPROC _glEvalCoord2fv;
extern PFNGLEVALMESH1GLPROC _glEvalMesh1;
extern PFNGLEVALMESH2GLPROC _glEvalMesh2;
extern PFNGLEVALPOINT1GLPROC _glEvalPoint1;
extern PFNGLEVALPOINT2GLPROC _glEvalPoint2;
extern PFNGLFEEDBACKBUFFERGLPROC _glFeedbackBuffer;
extern PFNGLFINISHGLPROC _glFinish;
extern PFNGLFLUSHGLPROC _glFlush;
extern PFNGLFOGFGLPROC _glFogf;
extern PFNGLFOGFVGLPROC _glFogfv;
extern PFNGLFOGIGLPROC _glFogi;
extern PFNGLFOGIVGLPROC _glFogiv;
extern PFNGLFRONTFACEGLPROC _glFrontFace;
extern PFNGLFRUSTUMGLPROC _glFrustum;
extern PFNGLGENLISTSGLPROC _glGenLists;
extern PFNGLGENTEXTURESGLPROC _glGenTextures;
extern PFNGLGETBOOLEANVGLPROC _glGetBooleanv;
extern PFNGLGETCLIPPLANEGLPROC _glGetClipPlane;
extern PFNGLGETDOUBLEVGLPROC _glGetDoublev;
extern PFNGLGETERRORGLPROC _glGetError;
extern PFNGLGETFLOATVGLPROC _glGetFloatv;
extern PFNGLGETINTEGERVGLPROC _glGetIntegerv;
extern PFNGLGETLIGHTFVGLPROC _glGetLightfv;
extern PFNGLGETLIGHTIVGLPROC _glGetLightiv;
extern PFNGLGETMAPDVGLPROC _glGetMapdv;
extern PFNGLGETMAPFVGLPROC _glGetMapfv;
extern PFNGLGETMAPIVGLPROC _glGetMapiv;
extern PFNGLGETMATERIALFVGLPROC _glGetMaterialfv;
extern PFNGLGETMATERIALIVGLPROC _glGetMaterialiv;
extern PFNGLGETPIXELMAPFVGLPROC _glGetPixelMapfv;
extern PFNGLGETPIXELMAPUIVGLPROC _glGetPixelMapuiv;
extern PFNGLGETPIXELMAPUSVGLPROC _glGetPixelMapusv;
extern PFNGLGETPOINTERVGLPROC _glGetPointerv;
extern PFNGLGETPOLYGONSTIPPLEGLPROC _glGetPolygonStipple;
extern PFNGLGETSTRINGGLPROC _glGetString;
extern PFNGLGETTEXENVFVGLPROC _glGetTexEnvfv;
extern PFNGLGETTEXENVIVGLPROC _glGetTexEnviv;
extern PFNGLGETTEXGENDVGLPROC _glGetTexGendv;
extern PFNGLGETTEXGENFVGLPROC _glGetTexGenfv;
extern PFNGLGETTEXGENIVGLPROC _glGetTexGeniv;
extern PFNGLGETTEXIMAGEGLPROC _glGetTexImage;
extern PFNGLGETTEXLEVELPARAMETERFVGLPROC _glGetTexLevelParameterfv;
extern PFNGLGETTEXLEVELPARAMETERIVGLPROC _glGetTexLevelParameteriv;
extern PFNGLGETTEXPARAMETERFVGLPROC _glGetTexParameterfv;
extern PFNGLGETTEXPARAMETERIVGLPROC _glGetTexParameteriv;
extern PFNGLHINTGLPROC _glHint;
extern PFNGLINDEXMASKGLPROC _glIndexMask;
extern PFNGLINDEXPOINTERGLPROC _glIndexPointer;
extern PFNGLINDEXDGLPROC _glIndexd;
extern PFNGLINDEXDVGLPROC _glIndexdv;
extern PFNGLINDEXFGLPROC _glIndexf;
extern PFNGLINDEXFVGLPROC _glIndexfv;
extern PFNGLINDEXIGLPROC _glIndexi;
extern PFNGLINDEXIVGLPROC _glIndexiv;
extern PFNGLINDEXSGLPROC _glIndexs;
extern PFNGLINDEXSVGLPROC _glIndexsv;
extern PFNGLINDEXUBGLPROC _glIndexub;
extern PFNGLINDEXUBVGLPROC _glIndexubv;
extern PFNGLINITNAMESGLPROC _glInitNames;
extern PFNGLINTERLEAVEDARRAYSGLPROC _glInterleavedArrays;
extern PFNGLISENABLEDGLPROC _glIsEnabled;
extern PFNGLISLISTGLPROC _glIsList;
extern PFNGLISTEXTUREGLPROC _glIsTexture;
extern PFNGLLIGHTMODELFGLPROC _glLightModelf;
extern PFNGLLIGHTMODELFVGLPROC _glLightModelfv;
extern PFNGLLIGHTMODELIGLPROC _glLightModeli;
extern PFNGLLIGHTMODELIVGLPROC _glLightModeliv;
extern PFNGLLIGHTFGLPROC _glLightf;
extern PFNGLLIGHTFVGLPROC _glLightfv;
extern PFNGLLIGHTIGLPROC _glLighti;
extern PFNGLLIGHTIVGLPROC _glLightiv;
extern PFNGLLINESTIPPLEGLPROC _glLineStipple;
extern PFNGLLINEWIDTHGLPROC _glLineWidth;
extern PFNGLLISTBASEGLPROC _glListBase;
extern PFNGLLOADIDENTITYGLPROC _glLoadIdentity;
extern PFNGLLOADMATRIXDGLPROC _glLoadMatrixd;
extern PFNGLLOADMATRIXFGLPROC _glLoadMatrixf;
extern PFNGLLOADNAMEGLPROC _glLoadName;
extern PFNGLLOGICOPGLPROC _glLogicOp;
extern PFNGLMAP1DGLPROC _glMap1d;
extern PFNGLMAP1FGLPROC _glMap1f;
extern PFNGLMAP2DGLPROC _glMap2d;
extern PFNGLMAP2FGLPROC _glMap2f;
extern PFNGLMAPGRID1DGLPROC _glMapGrid1d;
extern PFNGLMAPGRID1FGLPROC _glMapGrid1f;
extern PFNGLMAPGRID2DGLPROC _glMapGrid2d;
extern PFNGLMAPGRID2FGLPROC _glMapGrid2f;
extern PFNGLMATERIALFGLPROC _glMaterialf;
extern PFNGLMATERIALFVGLPROC _glMaterialfv;
extern PFNGLMATERIALIGLPROC _glMateriali;
extern PFNGLMATERIALIVGLPROC _glMaterialiv;
extern PFNGLMATRIXMODEGLPROC _glMatrixMode;
extern PFNGLMULTMATRIXDGLPROC _glMultMatrixd;
extern PFNGLMULTMATRIXFGLPROC _glMultMatrixf;
extern PFNGLNEWLISTGLPROC _glNewList;
extern PFNGLNORMAL3BGLPROC _glNormal3b;
extern PFNGLNORMAL3BVGLPROC _glNormal3bv;
extern PFNGLNORMAL3DGLPROC _glNormal3d;
extern PFNGLNORMAL3DVGLPROC _glNormal3dv;
extern PFNGLNORMAL3FGLPROC _glNormal3f;
extern PFNGLNORMAL3FVGLPROC _glNormal3fv;
extern PFNGLNORMAL3IGLPROC _glNormal3i;
extern PFNGLNORMAL3IVGLPROC _glNormal3iv;
extern PFNGLNORMAL3SGLPROC _glNormal3s;
extern PFNGLNORMAL3SVGLPROC _glNormal3sv;
extern PFNGLNORMALPOINTERGLPROC _glNormalPointer;
extern PFNGLORTHOGLPROC _glOrtho;
extern PFNGLPASSTHROUGHGLPROC _glPassThrough;
extern PFNGLPIXELMAPFVGLPROC _glPixelMapfv;
extern PFNGLPIXELMAPUIVGLPROC _glPixelMapuiv;
extern PFNGLPIXELMAPUSVGLPROC _glPixelMapusv;
extern PFNGLPIXELSTOREFGLPROC _glPixelStoref;
extern PFNGLPIXELSTOREIGLPROC _glPixelStorei;
extern PFNGLPIXELTRANSFERFGLPROC _glPixelTransferf;
extern PFNGLPIXELTRANSFERIGLPROC _glPixelTransferi;
extern PFNGLPIXELZOOMGLPROC _glPixelZoom;
extern PFNGLPOINTSIZEGLPROC _glPointSize;
extern PFNGLPOLYGONMODEGLPROC _glPolygonMode;
extern PFNGLPOLYGONOFFSETGLPROC _glPolygonOffset;
extern PFNGLPOLYGONSTIPPLEGLPROC _glPolygonStipple;
extern PFNGLPOPATTRIBGLPROC _glPopAttrib;
extern PFNGLPOPCLIENTATTRIBGLPROC _glPopClientAttrib;
extern PFNGLPOPMATRIXGLPROC _glPopMatrix;
extern PFNGLPOPNAMEGLPROC _glPopName;
extern PFNGLPRIORITIZETEXTURESGLPROC _glPrioritizeTextures;
extern PFNGLPUSHATTRIBGLPROC _glPushAttrib;
extern PFNGLPUSHCLIENTATTRIBGLPROC _glPushClientAttrib;
extern PFNGLPUSHMATRIXGLPROC _glPushMatrix;
extern PFNGLPUSHNAMEGLPROC _glPushName;
extern PFNGLRASTERPOS2DGLPROC _glRasterPos2d;
extern PFNGLRASTERPOS2DVGLPROC _glRasterPos2dv;
extern PFNGLRASTERPOS2FGLPROC _glRasterPos2f;
extern PFNGLRASTERPOS2FVGLPROC _glRasterPos2fv;
extern PFNGLRASTERPOS2IGLPROC _glRasterPos2i;
extern PFNGLRASTERPOS2IVGLPROC _glRasterPos2iv;
extern PFNGLRASTERPOS2SGLPROC _glRasterPos2s;
extern PFNGLRASTERPOS2SVGLPROC _glRasterPos2sv;
extern PFNGLRASTERPOS3DGLPROC _glRasterPos3d;
extern PFNGLRASTERPOS3DVGLPROC _glRasterPos3dv;
extern PFNGLRASTERPOS3FGLPROC _glRasterPos3f;
extern PFNGLRASTERPOS3FVGLPROC _glRasterPos3fv;
extern PFNGLRASTERPOS3IGLPROC _glRasterPos3i;
extern PFNGLRASTERPOS3IVGLPROC _glRasterPos3iv;
extern PFNGLRASTERPOS3SGLPROC _glRasterPos3s;
extern PFNGLRASTERPOS3SVGLPROC _glRasterPos3sv;
extern PFNGLRASTERPOS4DGLPROC _glRasterPos4d;
extern PFNGLRASTERPOS4DVGLPROC _glRasterPos4dv;
extern PFNGLRASTERPOS4FGLPROC _glRasterPos4f;
extern PFNGLRASTERPOS4FVGLPROC _glRasterPos4fv;
extern PFNGLRASTERPOS4IGLPROC _glRasterPos4i;
extern PFNGLRASTERPOS4IVGLPROC _glRasterPos4iv;
extern PFNGLRASTERPOS4SGLPROC _glRasterPos4s;
extern PFNGLRASTERPOS4SVGLPROC _glRasterPos4sv;
extern PFNGLREADBUFFERGLPROC _glReadBuffer;
extern PFNGLREADPIXELSGLPROC _glReadPixels;
extern PFNGLRECTDGLPROC _glRectd;
extern PFNGLRECTDVGLPROC _glRectdv;
extern PFNGLRECTFGLPROC _glRectf;
extern PFNGLRECTFVGLPROC _glRectfv;
extern PFNGLRECTIGLPROC _glRecti;
extern PFNGLRECTIVGLPROC _glRectiv;
extern PFNGLRECTSGLPROC _glRects;
extern PFNGLRECTSVGLPROC _glRectsv;
extern PFNGLRENDERMODEGLPROC _glRenderMode;
extern PFNGLROTATEDGLPROC _glRotated;
extern PFNGLROTATEFGLPROC _glRotatef;
extern PFNGLSCALEDGLPROC _glScaled;
extern PFNGLSCALEFGLPROC _glScalef;
extern PFNGLSCISSORGLPROC _glScissor;
extern PFNGLSELECTBUFFERGLPROC _glSelectBuffer;
extern PFNGLSHADEMODELGLPROC _glShadeModel;
extern PFNGLSTENCILFUNCGLPROC _glStencilFunc;
extern PFNGLSTENCILMASKGLPROC _glStencilMask;
extern PFNGLSTENCILOPGLPROC _glStencilOp;
extern PFNGLTEXCOORD1DGLPROC _glTexCoord1d;
extern PFNGLTEXCOORD1DVGLPROC _glTexCoord1dv;
extern PFNGLTEXCOORD1FGLPROC _glTexCoord1f;
extern PFNGLTEXCOORD1FVGLPROC _glTexCoord1fv;
extern PFNGLTEXCOORD1IGLPROC _glTexCoord1i;
extern PFNGLTEXCOORD1IVGLPROC _glTexCoord1iv;
extern PFNGLTEXCOORD1SGLPROC _glTexCoord1s;
extern PFNGLTEXCOORD1SVGLPROC _glTexCoord1sv;
extern PFNGLTEXCOORD2DGLPROC _glTexCoord2d;
extern PFNGLTEXCOORD2DVGLPROC _glTexCoord2dv;
extern PFNGLTEXCOORD2FGLPROC _glTexCoord2f;
extern PFNGLTEXCOORD2FVGLPROC _glTexCoord2fv;
extern PFNGLTEXCOORD2IGLPROC _glTexCoord2i;
extern PFNGLTEXCOORD2IVGLPROC _glTexCoord2iv;
extern PFNGLTEXCOORD2SGLPROC _glTexCoord2s;
extern PFNGLTEXCOORD2SVGLPROC _glTexCoord2sv;
extern PFNGLTEXCOORD3DGLPROC _glTexCoord3d;
extern PFNGLTEXCOORD3DVGLPROC _glTexCoord3dv;
extern PFNGLTEXCOORD3FGLPROC _glTexCoord3f;
extern PFNGLTEXCOORD3FVGLPROC _glTexCoord3fv;
extern PFNGLTEXCOORD3IGLPROC _glTexCoord3i;
extern PFNGLTEXCOORD3IVGLPROC _glTexCoord3iv;
extern PFNGLTEXCOORD3SGLPROC _glTexCoord3s;
extern PFNGLTEXCOORD3SVGLPROC _glTexCoord3sv;
extern PFNGLTEXCOORD4DGLPROC _glTexCoord4d;
extern PFNGLTEXCOORD4DVGLPROC _glTexCoord4dv;
extern PFNGLTEXCOORD4FGLPROC _glTexCoord4f;
extern PFNGLTEXCOORD4FVGLPROC _glTexCoord4fv;
extern PFNGLTEXCOORD4IGLPROC _glTexCoord4i;
extern PFNGLTEXCOORD4IVGLPROC _glTexCoord4iv;
extern PFNGLTEXCOORD4SGLPROC _glTexCoord4s;
extern PFNGLTEXCOORD4SVGLPROC _glTexCoord4sv;
extern PFNGLTEXCOORDPOINTERGLPROC _glTexCoordPointer;
extern PFNGLTEXENVFGLPROC _glTexEnvf;
extern PFNGLTEXENVFVGLPROC _glTexEnvfv;
extern PFNGLTEXENVIGLPROC _glTexEnvi;
extern PFNGLTEXENVIVGLPROC _glTexEnviv;
extern PFNGLTEXGENDGLPROC _glTexGend;
extern PFNGLTEXGENDVGLPROC _glTexGendv;
extern PFNGLTEXGENFGLPROC _glTexGenf;
extern PFNGLTEXGENFVGLPROC _glTexGenfv;
extern PFNGLTEXGENIGLPROC _glTexGeni;
extern PFNGLTEXGENIVGLPROC _glTexGeniv;
extern PFNGLTEXIMAGE1DGLPROC _glTexImage1D;
extern PFNGLTEXIMAGE2DGLPROC _glTexImage2D;
extern PFNGLTEXPARAMETERFGLPROC _glTexParameterf;
extern PFNGLTEXPARAMETERFVGLPROC _glTexParameterfv;
extern PFNGLTEXPARAMETERIGLPROC _glTexParameteri;
extern PFNGLTEXPARAMETERIVGLPROC _glTexParameteriv;
extern PFNGLTEXSUBIMAGE1DGLPROC _glTexSubImage1D;
extern PFNGLTEXSUBIMAGE2DGLPROC _glTexSubImage2D;
extern PFNGLTRANSLATEDGLPROC _glTranslated;
extern PFNGLTRANSLATEFGLPROC _glTranslatef;
extern PFNGLVERTEX2DGLPROC _glVertex2d;
extern PFNGLVERTEX2DVGLPROC _glVertex2dv;
extern PFNGLVERTEX2FGLPROC _glVertex2f;
extern PFNGLVERTEX2FVGLPROC _glVertex2fv;
extern PFNGLVERTEX2IGLPROC _glVertex2i;
extern PFNGLVERTEX2IVGLPROC _glVertex2iv;
extern PFNGLVERTEX2SGLPROC _glVertex2s;
extern PFNGLVERTEX2SVGLPROC _glVertex2sv;
extern PFNGLVERTEX3DGLPROC _glVertex3d;
extern PFNGLVERTEX3DVGLPROC _glVertex3dv;
extern PFNGLVERTEX3FGLPROC _glVertex3f;
extern PFNGLVERTEX3FVGLPROC _glVertex3fv;
extern PFNGLVERTEX3IGLPROC _glVertex3i;
extern PFNGLVERTEX3IVGLPROC _glVertex3iv;
extern PFNGLVERTEX3SGLPROC _glVertex3s;
extern PFNGLVERTEX3SVGLPROC _glVertex3sv;
extern PFNGLVERTEX4DGLPROC _glVertex4d;
extern PFNGLVERTEX4DVGLPROC _glVertex4dv;
extern PFNGLVERTEX4FGLPROC _glVertex4f;
extern PFNGLVERTEX4FVGLPROC _glVertex4fv;
extern PFNGLVERTEX4IGLPROC _glVertex4i;
extern PFNGLVERTEX4IVGLPROC _glVertex4iv;
extern PFNGLVERTEX4SGLPROC _glVertex4s;
extern PFNGLVERTEX4SVGLPROC _glVertex4sv;
extern PFNGLVERTEXPOINTERGLPROC _glVertexPointer;
extern PFNGLVIEWPORTGLPROC _glViewport;
extern PFNWGLUSEFONTOUTLINESAGLPROC _wglUseFontOutlinesA;
extern PFNWGLUSEFONTOUTLINESWGLPROC _wglUseFontOutlinesW;
extern PFNWGLUSEFONTBITMAPSAGLPROC _wglUseFontBitmapsA;
extern PFNWGLUSEFONTBITMAPSWGLPROC _wglUseFontBitmapsW;
extern PFNWGLCOPYCONTEXTGLPROC _wglCopyContext;
extern PFNWGLCREATECONTEXTGLPROC _wglCreateContext;
extern PFNWGLCREATELAYERCONTEXTGLPROC _wglCreateLayerContext;
extern PFNWGLDELETECONTEXTGLPROC _wglDeleteContext;
extern PFNWGLGETCURRENTCONTEXTGLPROC _wglGetCurrentContext;
extern PFNWGLGETCURRENTDCGLPROC _wglGetCurrentDC;
extern PFNWGLGETPROCADDRESSGLPROC _wglGetProcAddress;
extern PFNWGLMAKECURRENTGLPROC _wglMakeCurrent;
extern PFNWGLSHARELISTSGLPROC _wglShareLists;
extern PFNWGLDESCRIBELAYERPLANEGLPROC _wglDescribeLayerPlane;
extern PFNWGLSETLAYERPALETTEENTRIESGLPROC _wglSetLayerPaletteEntries;
extern PFNWGLGETLAYERPALETTEENTRIESGLPROC _wglGetLayerPaletteEntries;
extern PFNWGLREALIZELAYERPALETTEGLPROC _wglRealizeLayerPalette;
extern PFNWGLSWAPLAYERBUFFERSGLPROC _wglSwapLayerBuffers;
extern PFNWGLCHOOSEPIXELFORMATGLPROC _wglChoosePixelFormat;
extern PFNWGLDESCRIBEPIXELFORMATGLPROC _wglDescribePixelFormat;
extern PFNWGLGETPIXELFORMATGLPROC _wglGetPixelFormat;
extern PFNWGLSETPIXELFORMATGLPROC _wglSetPixelFormat;
extern PFNWGLSWAPBUFFERSGLPROC _wglSwapBuffers;
extern PFNWGLGETDEFAULTPROCADDRESSGLPROC _wglGetDefaultProcAddress;
extern PFNDRVCOPYCONTEXTGLPROC _DrvCopyContext;
extern PFNDRVCREATECONTEXTGLPROC _DrvCreateContext;
extern PFNDRVCREATELAYERCONTEXTGLPROC _DrvCreateLayerContext;
extern PFNDRVDELETECONTEXTGLPROC _DrvDeleteContext;
extern PFNDRVDESCRIBELAYERPLANEGLPROC _DrvDescribeLayerPlane;
extern PFNDRVDESCRIBEPIXELFORMATGLPROC _DrvDescribePixelFormat;
extern PFNDRVSETLAYERPALETTEENTRIESGLPROC _DrvSetLayerPaletteEntries;
extern PFNDRVGETLAYERPALETTEENTRIESGLPROC _DrvGetLayerPaletteEntries;
extern PFNDRVREALIZELAYERPALETTEGLPROC _DrvRealizeLayerPalette;
extern PFNDRVSWAPLAYERBUFFERSGLPROC _DrvSwapLayerBuffers;
extern PFNDRVSHARELISTSGLPROC _DrvShareLists;
extern PFNDRVSETPIXELFORMATGLPROC _DrvSetPixelFormat;
extern PFNDRVSWAPBUFFERSGLPROC _DrvSwapBuffers;
extern PFNDRVGETPROCADDRESSGLPROC _DrvGetProcAddress;
extern PFNDRVSETCONTEXTGLPROC _DrvSetContext;
extern PFNDRVRELEASECONTEXTGLPROC _DrvReleaseContext;
extern PFNDRVVALIDATEVERSIONGLPROC _DrvValidateVersion;

struct GLOPT
{
 char name[32];
 int value;
};

extern GLOPT glopt[];

// контекст
struct GLRBCONTEXT
{
 // признак создания GL контекста
 GLboolean makecontext;

 // список текстур
 DYNARRAY* textures;
 // текущая текстура
 unsigned int current_texture;

 //////////////////////////////////////////////////////////////////////
 // параметры для glGet
 

 // GL_ARB_multisample
 GLclampf ARB_multisample_value;
 GLboolean ARB_multisample_invert;

 //////////////////////////////////////////////////////////////////////
 // параметры для glEnable/glDisable 
 //             и glEnableClientState/glDisableClientState

 // GL_ARB_multisample
 GLboolean gl_SAMPLE_ALPHA_TO_COVERAGE_ARB;
 GLboolean gl_SAMPLE_ALPHA_TO_ONE_ARB;
 GLboolean gl_SAMPLE_COVERAGE_ARB;

 // GL_EXT_rescale_normal
 GLboolean gl_RESCALE_NORMAL_EXT;
 GLboolean gl_NORMALIZE;

 // GL_ARB_point_sprite
 GLboolean gl_POINT_SPRITE_ARB;

 // GL_NV_vertex_array_range
 GLboolean gl_VERTEX_ARRAY_RANGE_NV;
 // GL_NV_vertex_array_range2
 GLboolean gl_VERTEX_ARRAY_RANGE_WITHOUT_FLUSH_NV;
 // GL_NV_pixel_data_range
 GLboolean gl_WRITE_PIXEL_DATA_RANGE_NV;
 GLboolean gl_READ_PIXEL_DATA_RANGE_NV;

 //////////////////////////////////////////////////////////////////////
 // параметры для glHint
 
 // GL_SGIS_generate_mipmap
 GLenum SGIS_generate_mipmaps_hint;

 // GL_NV_multisample_filter_hint
 GLenum NV_multisample_filter_hint;

};

extern GLRBCONTEXT ctx;

#endif
