#ifndef __WINDOWS_POS_H_
#define __WINDOWS_POS_H_

GLAPI void APIENTRY glWindowPos4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
GLAPI void APIENTRY glWindowPos2d(GLdouble x, GLdouble y);
GLAPI void APIENTRY glWindowPos2dv(const GLdouble *v);
GLAPI void APIENTRY glWindowPos2f(GLfloat x, GLfloat y);
GLAPI void APIENTRY glWindowPos2fv(const GLfloat *v);
GLAPI void APIENTRY glWindowPos2i(GLint x, GLint y);
GLAPI void APIENTRY glWindowPos2iv(const GLint *v);
GLAPI void APIENTRY glWindowPos2s(GLshort x, GLshort y);
GLAPI void APIENTRY glWindowPos2sv(const GLshort *v);
GLAPI void APIENTRY glWindowPos3d(GLdouble x, GLdouble y, GLdouble z);
GLAPI void APIENTRY glWindowPos3dv(const GLdouble *v);
GLAPI void APIENTRY glWindowPos3f(GLfloat x, GLfloat y, GLfloat z);
GLAPI void APIENTRY glWindowPos3fv(const GLfloat *v);
GLAPI void APIENTRY glWindowPos3i(GLint x, GLint y, GLint z);
GLAPI void APIENTRY glWindowPos3iv(const GLint *v);
GLAPI void APIENTRY glWindowPos3s(GLshort x, GLshort y, GLshort z);
GLAPI void APIENTRY glWindowPos3sv(const GLshort *v);
GLAPI void APIENTRY glWindowPos4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
GLAPI void APIENTRY glWindowPos4dv(const GLdouble *v);
GLAPI void APIENTRY glWindowPos4fv(const GLfloat *v);
GLAPI void APIENTRY glWindowPos4i(GLint x, GLint y, GLint z, GLint w);
GLAPI void APIENTRY glWindowPos4iv(const GLint *v);
GLAPI void APIENTRY glWindowPos4s(GLshort x, GLshort y, GLshort z, GLshort w);
GLAPI void APIENTRY glWindowPos4sv(const GLshort *v);

#endif